<?php

// Theme presets: one component system, token overrides only.
// Each preset overrides CSS custom properties defined in resources/css/app.css.

use Illuminate\Support\Js;

return [
    'default' => 'editorial',

    'presets' => [
        'editorial' => [
            'label' => 'Editorial',
            'description' => 'Warm paper, serif display, terracotta accent. Default character of the platform.',
            'vars' => [
                '--color-paper' => '#f6f4ef',
                '--color-surface' => '#ffffff',
                '--color-surface-2' => '#efede6',
                '--color-ink' => '#1b1813',
                '--color-ink-2' => '#565047',
                '--color-ink-3' => '#8d867b',
                '--color-line' => '#e4e0d5',
                '--color-line-strong' => '#d4cfc1',
                '--color-accent' => '#9a4a2b',
                '--color-accent-ink' => '#7c3a21',
                '--color-accent-soft' => '#f4e6de',
                '--font-sans' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--font-display' => "'Instrument Serif', Georgia, serif",
                '--radius-md' => '0.5rem',
                '--radius-lg' => '0.75rem',
                '--radius-xl' => '1rem',
            ],
        ],
        'minimal' => [
            'label' => 'Minimal',
            'description' => 'Pure white, near-black ink, quiet gray lines. Zero-decor restraint.',
            'vars' => [
                '--color-paper' => '#ffffff',
                '--color-surface' => '#ffffff',
                '--color-surface-2' => '#f4f4f5',
                '--color-ink' => '#111113',
                '--color-ink-2' => '#52525b',
                '--color-ink-3' => '#9ca3af',
                '--color-line' => '#e4e4e7',
                '--color-line-strong' => '#d4d4d8',
                '--color-accent' => '#111113',
                '--color-accent-ink' => '#000000',
                '--color-accent-soft' => '#f4f4f5',
                '--font-sans' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--font-display' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--radius-md' => '0.25rem',
                '--radius-lg' => '0.375rem',
                '--radius-xl' => '0.5rem',
            ],
        ],
        'luxury' => [
            'label' => 'Luxury',
            'description' => 'Ivory, charcoal ink, deep bronze accent. Wide tracking, formal spacing.',
            'vars' => [
                '--color-paper' => '#faf8f4',
                '--color-surface' => '#ffffff',
                '--color-surface-2' => '#f1ede5',
                '--color-ink' => '#1c1a17',
                '--color-ink-2' => '#57524a',
                '--color-ink-3' => '#8f887c',
                '--color-line' => '#e5dfd3',
                '--color-line-strong' => '#d3cab8',
                '--color-accent' => '#8a6d3b',
                '--color-accent-ink' => '#6e5528',
                '--color-accent-soft' => '#f2ead9',
                '--font-sans' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--font-display' => "'Instrument Serif', Georgia, serif",
                '--radius-md' => '0.125rem',
                '--radius-lg' => '0.25rem',
                '--radius-xl' => '0.375rem',
            ],
        ],
        'fashion' => [
            'label' => 'Fashion',
            'description' => 'Cold white, pure black, punchy fuchsia accent. Display-heavy.',
            'vars' => [
                '--color-paper' => '#fdfdfd',
                '--color-surface' => '#ffffff',
                '--color-surface-2' => '#f5f5f6',
                '--color-ink' => '#0a0a0b',
                '--color-ink-2' => '#4b4b52',
                '--color-ink-3' => '#8e8e96',
                '--color-line' => '#e7e7ea',
                '--color-line-strong' => '#d7d7db',
                '--color-accent' => '#c53080',
                '--color-accent-ink' => '#9d2467',
                '--color-accent-soft' => '#fbe4f0',
                '--font-sans' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--font-display' => "'Instrument Serif', Georgia, serif",
                '--radius-md' => '0',
                '--radius-lg' => '0',
                '--radius-xl' => '0.25rem',
            ],
        ],
        'tech' => [
            'label' => 'Tech',
            'description' => 'Cool slate, indigo accent, slightly rounded functional shapes.',
            'vars' => [
                '--color-paper' => '#f8fafc',
                '--color-surface' => '#ffffff',
                '--color-surface-2' => '#f1f5f9',
                '--color-ink' => '#0f172a',
                '--color-ink-2' => '#475569',
                '--color-ink-3' => '#94a3b8',
                '--color-line' => '#e2e8f0',
                '--color-line-strong' => '#cbd5e1',
                '--color-accent' => '#4f46e5',
                '--color-accent-ink' => '#4338ca',
                '--color-accent-soft' => '#e0e7ff',
                '--font-sans' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--font-display' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--radius-md' => '0.5rem',
                '--radius-lg' => '0.75rem',
                '--radius-xl' => '1rem',
            ],
        ],
        'market' => [
            'label' => 'Market',
            'description' => 'Cream paper, forest green accent — fresh, friendly commerce.',
            'vars' => [
                '--color-paper' => '#fbf8f0',
                '--color-surface' => '#ffffff',
                '--color-surface-2' => '#f0ecdf',
                '--color-ink' => '#20301f',
                '--color-ink-2' => '#4c5a4b',
                '--color-ink-3' => '#8b968a',
                '--color-line' => '#e3e2d2',
                '--color-line-strong' => '#d1d0ba',
                '--color-accent' => '#2f7d4f',
                '--color-accent-ink' => '#25633f',
                '--color-accent-soft' => '#e3f2e8',
                '--font-sans' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--font-display' => "'Instrument Serif', Georgia, serif",
                '--radius-md' => '0.5rem',
                '--radius-lg' => '0.75rem',
                '--radius-xl' => '1rem',
            ],
        ],
        'bold' => [
            'label' => 'Bold',
            'description' => 'Ink-on-sand flipped contrast: dark surfaces, bright citrus accent.',
            'vars' => [
                '--color-paper' => '#16181d',
                '--color-surface' => '#1e2128',
                '--color-surface-2' => '#262a33',
                '--color-ink' => '#f4f5f7',
                '--color-ink-2' => '#b7bcc7',
                '--color-ink-3' => '#7f8593',
                '--color-line' => '#333845',
                '--color-line-strong' => '#414858',
                '--color-accent' => '#f5b83d',
                '--color-accent-ink' => '#e09f1f',
                '--color-accent-soft' => '#3a3117',
                '--font-sans' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--font-display' => "'Instrument Sans', ui-sans-serif, system-ui, sans-serif",
                '--radius-md' => '0.5rem',
                '--radius-lg' => '0.75rem',
                '--radius-xl' => '1rem',
            ],
        ],
    ],

    /**
     * Keys the admin may override per-store on top of the active preset.
     */
    'overridable' => [
        '--color-paper' => ['label' => 'Latar Belakang', 'type' => 'color'],
        '--color-accent' => ['label' => 'Warna Aksen', 'type' => 'color'],
        '--color-ink' => ['label' => 'Warna Teks', 'type' => 'color'],
    ],
];
